version: '2'

services:
    # mysql:
    #     build: ./mysql
    #     ports:
    #         - '3306:3306'
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    # apache:
    #     build: ./apache
    #     ports: 
    #         - '8888:80'
    #     volumes:
    #         - ./logs/apache:/var/log/apache2
    #         - ./src:/var/www/html
    #     # links: 
    #     #     - mysql
    # nginx:
    #     build: ./nginx
    #     ports:
    #         - '80:80'
    #     volumes:
    #         - './src:/var/www/html'
    #     links:
    #         - phpfpm
    # phpfpm:
    #     image: 'php:7-fpm'
    #     volumes:
    #         - './src:/var/www/html'
    # mysql:
    #     image: 'mariadb'
    #     ports:
    #         - '3306:3306'
    #     volumes:
    #         - ./logs/db:/var/lib/mysql
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=root
    # phpmyadmin:
    #     image: 'phpmyadmin/phpmyadmin'
    #     restart: always
    #     ports:
    #        - '8080:80'
    #     links:
    #         - mysql:mysql
    #     environment:
    #         MYSQL_USERNAME: root
    #         MYSQL_ROOT_PASSWORD: root
    #         PMA_HOST: mysql

    ########################
    # ngnode:
    #     build: ./ngnode
    # reactnode:
    #     build: ./reactnode

    ######################## 
    figured:
        image: hitalos/laravel:latest
        ports: 
            - '80:80'
        volumes:
            - './src/figured:/var/www'
        links:
            - db
        environment:
            DB_HOST: db
            DB_DATABASE: figured
            DB_USERNAME: user
            DB_PASSWORD: password
            DB_CONNECTION: mysql
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: figured
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password