version: '2'

services:
    db:
        build: ./mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
    php:
        build: ./apache
        ports: 
            - '80:80'
        volumes:
            - ./src:/var/www/html
        links: 
            - db